# Generated by Django 2.0.8 on 2019-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_auto_20190126_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keyword', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
